### ISSUE TITLE
Array.prototype.flat is not a function

### ISSUE THREAD

**Issue by CJN1986** [3846masa/upload-gphotos#443]
```bash
# npm install -g upload-gphotos

/usr/bin/upload-gphotos -> /usr/lib/node_modules/upload-gphotos/lib/cli/index.js

> puppeteer-core@2.0.0 install /usr/lib/node_modules/upload-gphotos/node_modules/puppeteer-core
> node install.js

npm WARN puppeteer-extra@3.1.9 requires a peer of puppeteer@* but none is installed. You must install peer dependencies yourself.

+ upload-gphotos@4.0.0
added 177 packages from 170 contributors in 9.985s
```

ubuntu 18.04LTS
npm 6.13.4
upload-gphotos 4.0.0
chromium 79.0.3945.79

**Comment by 3846masa** [comment]
It seems to be succeeded to install.
`npm WARN` is warning, not be error.

**Comment by CJN1986** [comment]
```bash
upload-gphotos -v

/usr/lib/node_modules/upload-gphotos/lib/get_chrome_path.js:20
    .flat();
     ^

TypeError: ["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","/Applications/Chromium.app/Contents/MacOS/Chromium"].map(...).flat is not a function
    at Object.<anonymous> (/usr/lib/node_modules/upload-gphotos/lib/get_chrome_path.js:20:6)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/upload-gphotos/lib/signin_via_puppeteer.js:8:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

```
It seems to be succeeded to install, but can't running.

**Comment by 3846masa** [comment]
It is not an install error.
Array.prototype.flat cannot use in Node.js < v11.0
Please use Node.js v11 or greater version.

**Comment by CJN1986** [comment]
Yes, nodejs version was v10.18.0
It working now, when i update to v11.15.0.
